apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-cost-optimizer.fullname" . }}-config
data:
  config.yaml: |-
{{ .Files.Get "configs/config.yaml" | indent 4 }}
  pricing.yaml: |-
{{ .Files.Get "configs/pricing.yaml" | indent 4 }}
